import sys

sys.stdout.write("  ___  ___  ___\n")
sys.stdout.write("  | |__| |__| |\n")
sys.stdout.write("  |           |\n")
sys.stdout.write("   \\_________/\n")
sys.stdout.write("    \\_______/\n")
sys.stdout.write("     |     |\n")
sys.stdout.write("     |     |\n")
sys.stdout.write("     |     |\n")
sys.stdout.write("     |     |\n")
sys.stdout.write("     |_____|\n")
sys.stdout.write("  __/       \\__\n")
sys.stdout.write(" /             \\\n")
sys.stdout.write("/_______________\\\n")